GET https://api.themoviedb.org/3/movie/now_playing?api_key={{tmdb_key}}&include_adult=false&page=1 HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

###

@QUERY="now"
GET https://api.themoviedb.org/3/search/movie?api_key={{tmdb_key}}&language=en-US&page=1&include_adult=false&query={{QUERY}} HTTP/1.1
User-Agent: rest-client
Content-Type: application/json
