@BASE_URL=https://api.themoviedb.org/3

GET {{BASE_URL}}/movie/now_playing?api_key={{tmdb_key}}
User-Agent: rest-client
Content-Type: application/json

###

@QUERY="Top Gun"
@PAGE=1
GET {{BASE_URL}}/search/movie?api_key={{tmdb_key}}&page={{PAGE}}&query={{QUERY}}
User-Agent: rest-client
Content-Type: application/json



###

@MOVIE_ID=978444

GET {{BASE_URL}}/movie/{{MOVIE_ID}}?api_key={{tmdb_key}}
User-Agent: rest-client
Content-Type: application/json
